- name: Ensure github-runner user exists
  ansible.builtin.user:
    name: github-runner
    shell: /bin/bash
    create_home: true
    groups: docker
    append: true

- name: Build runner definitions
  ansible.builtin.set_fact:
    github_runner_definitions: >-
      {{
        github_runners
        | default([
            {
              'repo': github_runner_repo,
              'name': github_runner_name,
              'labels': github_runner_labels,
              'directory': '/opt/actions-runner'
            }
          ])
      }}

- name: Download actions runner
  ansible.builtin.get_url:
    url: "https://github.com/actions/runner/releases/download/v{{ github_runner_version }}/actions-runner-linux-x64-{{ github_runner_version }}.tar.gz"
    dest: "/tmp/actions-runner-linux-x64-{{ github_runner_version }}.tar.gz"
    mode: "0644"

- name: Configure GitHub runners
  ansible.builtin.include_tasks: runner.yml
  loop: "{{ github_runner_definitions }}"
  loop_control:
    loop_var: github_runner_item
    label: "{{ github_runner_item.repo }}"
